In [1]:
import torch
from torch_geometric.data import Data, DataLoader

In [9]:
from torch.nn import CrossEntropyLoss

loss_func = CrossEntropyLoss()

In [10]:
label = torch.tensor([0, 1, 1, 0, 0, 1], dtype=torch.long)


In [11]:
preds = torch.tensor([[1.0000e+00, 1.8162e-41],
        [4.7613e-18, 1.0000e+00],
        [8.7935e-26, 1.0000e+00],
        [1.0000e+00, 2.8026e-45],
        [1.0000e+00, 6.9294e-36],
        [9.8532e-24, 1.0000e+00]])

In [12]:
loss_func(preds, label)

tensor(0.3133)

In [17]:
preds_new =  torch.tensor([[100000.0, 0.0],
        [0, 100000],
        [0, 100000],
        [100000, 0],
        [100000, 0],
        [0, 100000]])

In [18]:
loss_func(preds_new, label)

tensor(0.)

In [4]:
class PairData(Data):
    def __init__(self, edge_index_s, x_s, edge_index_t, x_t):
        super(PairData, self).__init__()
        self.edge_index_s = edge_index_s
        self.x_s = x_s
        self.edge_index_t = edge_index_t
        self.x_t = x_t
    
    def __inc__(self, key, value):
        if key == 'edge_index_s':
            return self.x_s.size(0)
        if key == 'edge_index_t':
            return self.x_t.size(0)
        else:
            return super().__inc__(key, value)

edge_index_s = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
])
x_s = torch.randn(5, 16)  # 5 nodes.
edge_index_t = torch.tensor([
    [0, 0, 0],
    [1, 2, 3],
])
x_t = torch.randn(4, 16)  # 4 nodes.

data = PairData(edge_index_s, x_s, edge_index_t, x_t)
data_list = [data, data]
loader = DataLoader(data_list, batch_size=2)
batch = next(iter(loader))

print(batch)
print(batch.edge_index_s)
print(batch.edge_index_t)

Batch(edge_index_s=[2, 8], edge_index_t=[2, 6], x_s=[10, 16], x_t=[8, 16])
tensor([[0, 0, 0, 0, 5, 5, 5, 5],
        [1, 2, 3, 4, 6, 7, 8, 9]])
tensor([[0, 0, 0, 4, 4, 4],
        [1, 2, 3, 5, 6, 7]])


In [2]:
edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)

In [23]:
2/(1/0.978 + 1/0.975)

0.6922743682310469

In [4]:
data_list = [data, data]
loader = DataLoader(data_list, batch_size=2)

In [5]:
batch = next(iter(loader))

In [6]:
batch.ptr

tensor([0, 3, 6])

In [7]:
batch.batch

tensor([0, 0, 0, 1, 1, 1])

In [8]:
batch.batch.size(0)

6

In [5]:
print(type(edge_index_s))
print(type(x_s))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [6]:
print(type(edge_index_t))
print(type(x_t))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
